### ISSUE TITLE
Android Agent only installs CA

### ISSUE THREAD

**Issue by rokkhan** [inverse-inc/packetfence-android-agent#4]
I am trying to generate certificates through packetefence-pki and install them in Android using packetence app. 
I have an android 6.0 device where I launch the packetfence agent, says that profile has been downloaded, then it asks me for the password and after that shows a popup showing the CA certificate to install as a VPN and app or for WLAN. Every option I choose says the same "SSID has been created" but when I see my wlan configuration there is no any SSID generated.

**Comment by julsemaan** [comment]
We'll have to replicate in lab to see if its an Android agent issue or a PacketFence issue

Please provide the exact device information (manufacturer and model) and exact version of Android

**Comment by rokkhan** [comment]
Hi,
My mobile phone is a Meizu M5 Note Model M621H and the version is Flyme 5.2.11.1G
Greetings!

**Comment by julsemaan** [comment]
I'll also need the exact version of Android please

Thanks!

**Comment by rokkhan** [comment]
Hi,
I updated the OS to Android 6 and solved the issue. 
Thanks.
